dataset_path: /home/jingqi/DeepLearningWorkshop/dataset/CIFAR-10/raw/
epochs: 10
eval_batch: 256
eval_steps: 50
lr: 0.029685742426134584
model_layer: 50
num_classes: 10
optimizer_type: Adam
res_path: /home/jingqi/DeepLearningWorkshop/results/research_on_optimizer/Adam/config_11
train_batch: 128
