dataset_path: /home/ubuntu/DeepLearningWorkshop/dataset/CIFAR-10/raw/
epochs: 2
eval_batch: 256
eval_steps: 50
lr: 0.022250695589586377
model_layer: 18
momentum: 0.8548410789817957
num_classes: 10
optimizer_type: sgd_with_momentum
res_path: /home/ubuntu/DeepLearningWorkshop/results/research_on_optimizer/round2/sgd_with_momentum/config_1
train_batch: 128
