dataset_path: /home/jingqi/DeepLearningWorkshop/dataset/CIFAR-10/raw/
epochs: 10
eval_batch: 256
eval_steps: 50
lr: 0.01946008002281394
model_layer: 50
momentum: 0.8390305333668926
num_classes: 10
optimizer_type: sgd_with_momentum
res_path: /home/jingqi/DeepLearningWorkshop/results/research_on_optimizer/round2/sgd_with_momentum/config_2
train_batch: 128
