dataset_path: /home/jingqi/DeepLearningWorkshop/dataset/CIFAR-10/raw/
epochs: 10
eval_batch: 256
eval_steps: 50
lr: 0.037141191950982484
model_layer: 50
num_classes: 10
optimizer_type: NAdam
res_path: /home/jingqi/DeepLearningWorkshop/results/research_on_optimizer/round2/NAdam/config_10
train_batch: 128
