dataset_path: /home/ubuntu/DeepLearningWorkshop/dataset/CIFAR-10/raw/
epochs: 10
eval_batch: 256
eval_steps: 50
lr: 0.0014532782060360306
model_layer: 50
num_classes: 10
optimizer_type: AdamW
res_path: /home/ubuntu/DeepLearningWorkshop/results/research_on_optimizer/AdamW/config_3
train_batch: 128
