dataset_path: /home/ubuntu/DeepLearningWorkshop/dataset/CIFAR-10/raw/
data_augmentation:
  color_jitter: false
  gaussian_blur: false
  random_crop: false
  random_horizontal_filp: false
  random_rotate: false
weight_decay: 5.0e-04
epochs: 50
eval_batch: 256
eval_steps: 100
log_steps: 50
lr: 0.001
momentum: 0.9
model_layer: 18
num_classes: 10
optimizer_type: Nestrov
res_path: /home/ubuntu/DeepLearningWorkshop/results/test/
train_batch: 128

