dataset_path: /home/jingqi/DeepLearningWorkshop/dataset/CIFAR-10/raw/
weight_decay: 1.0e-04
epochs: 80
eval_batch: 256
eval_steps: 50
log_steps: 10
lr: 0.1
momentum: 0.9
model_layer: 18
num_classes: 10
optimizer_type: sgd_with_momentum
res_path: /home/jingqi/DeepLearningWorkshop/results/research_on_schedule/round1/config_0
train_batch: 128
