data_augmentation:
  color_jitter: false
  gaussian_blur: false
  random_crop: true
  random_horizontal_filp: true
  random_rotate: false
activation: silu
dataset_path: /home/ubuntu/DeepLearningWorkshop/dataset/CIFAR-10/raw/
epochs: 100
eval_batch: 256
eval_steps: 200
log_steps: 100
lr: 0.001
lr_schedule: cosine
warmup_steps: 1000
model_layer: 18
num_classes: 10
optimizer_type: Adam
res_path: /home/ubuntu/DeepLearningWorkshop/results/research_on_best/round7/config_6
train_batch: 128
weight_decay: 0.0003