dataset_path: /home/ubuntu/DeepLearningWorkshop/dataset/CIFAR-10/raw/
epochs: 20
eval_batch: 256
eval_steps: 50
log_steps: 10
lr: 0.001
model_layer: 18
num_classes: 10
optimizer_type: Adam
res_path: /home/ubuntu/DeepLearningWorkshop/results/research_on_regularization/round1/weight_decay/config_3
train_batch: 128
weight_decay: 0.0001
