dataset_path: /home/jingqi/DeepLearningWorkshop/dataset/CIFAR-10/raw/
epochs: 10
eval_batch: 256
eval_steps: 50
lr: 0.041643835560375785
model_layer: 50
num_classes: 10
optimizer_type: Adam
res_path: /home/jingqi/DeepLearningWorkshop/results/research_on_optimizer/round2/Adam/config_7
train_batch: 128
