dataset_path: /home/jingqi/DeepLearningWorkshop/dataset/CIFAR-10/raw/
epochs: 10
eval_batch: 256
eval_steps: 50
lr: 0.07884189292650798
model_layer: 50
momentum: 0.6131153337762743
num_classes: 10
optimizer_type: RMSprop
res_path: /home/jingqi/DeepLearningWorkshop/results/research_on_optimizer/RMSprop/config_12
train_batch: 128
