dataset_path: /home/jingqi/DeepLearningWorkshop/dataset/CIFAR-10/raw/
epochs: 10
eval_batch: 256
eval_steps: 50
lr: 0.08502939292650798
model_layer: 50
momentum: 0.7945968152577558
num_classes: 10
optimizer_type: RMSprop
res_path: /home/jingqi/DeepLearningWorkshop/results/research_on_optimizer/RMSprop/config_4
train_batch: 128
