dataset_path: /home/jingqi/DeepLearningWorkshop/dataset/CIFAR-10/raw/
epochs: 10
eval_batch: 256
eval_steps: 50
lr: 0.004591892926507977
model_layer: 50
momentum: 0.5586708893318298
num_classes: 10
optimizer_type: RMSprop
res_path: /home/jingqi/DeepLearningWorkshop/results/research_on_optimizer/RMSprop/config_15
train_batch: 128
