dataset_path: /home/jingqi/DeepLearningWorkshop/dataset/CIFAR-10/raw/
epochs: 10
eval_batch: 256
eval_steps: 50
lr: 0.04824504524482355
model_layer: 50
num_classes: 10
optimizer_type: AdamW
res_path: /home/jingqi/DeepLearningWorkshop/results/research_on_optimizer/AdamW/config_8
train_batch: 128
