dataset_path: /home/ubuntu/DeepLearningWorkshop/dataset/CIFAR-10/raw/
epochs: 2
eval_batch: 256
eval_steps: 50
lr: 0.0012033360583976439
model_layer: 18
momentum: 0.8958851692909395
num_classes: 10
optimizer_type: RMSprop
res_path: /home/ubuntu/DeepLearningWorkshop/results/research_on_optimizer/round2/RMSprop/config_1
train_batch: 128
