dataset_path: /home/ubuntu/DeepLearningWorkshop/dataset/CIFAR-10/raw/
epochs: 2
eval_batch: 256
eval_steps: 50
lr: 0.004859586058397643
model_layer: 18
momentum: 0.9732925766983469
num_classes: 10
optimizer_type: RMSprop
res_path: /home/ubuntu/DeepLearningWorkshop/results/research_on_optimizer/round2/RMSprop/config_12
train_batch: 128
