dataset_path: /home/ubuntu/DeepLearningWorkshop/dataset/CIFAR-10/raw/
epochs: 2
eval_batch: 256
eval_steps: 50
lr: 0.00857006100096882
model_layer: 18
momentum: 0.995176225367021
num_classes: 10
optimizer_type: RMSprop
res_path: /home/ubuntu/DeepLearningWorkshop/results/research_on_optimizer/round3/RMSprop/config_6
train_batch: 128
