dataset_path: /home/jingqi/DeepLearningWorkshop/dataset/CIFAR-10/raw/
dropout: 0.5
epochs: 20
eval_batch: 256
eval_steps: 50
log_steps: 10
lr: 0.001
model_layer: 18
num_classes: 10
optimizer_type: Adam
res_path: /home/jingqi/DeepLearningWorkshop/results/research_on_regularization/round1/dropout/config_5
train_batch: 128
