dataset_path: /home/jingqi/DeepLearningWorkshop/dataset/CIFAR-10/raw/
epochs: 10
eval_batch: 256
eval_steps: 50
lr: 0.021086411635780063
model_layer: 50
num_classes: 10
optimizer_type: sgd
res_path: /home/jingqi/DeepLearningWorkshop/results/research_on_optimizer/sgd/config_13
train_batch: 128
