data_augmentation:
  color_jitter: false
  gaussian_blur: false
  random_crop: false
  random_horizontal_filp: false
  random_rotate: false
dataset_path: /home/ubuntu/DeepLearningWorkshop/dataset/CIFAR-10/raw/
epochs: 40
eval_batch: 256
eval_steps: 100
log_steps: 50
lr: 0.0010923948609567375
model_layer: 18
num_classes: 10
optimizer_type: Adam
res_path: /home/ubuntu/DeepLearningWorkshop/results/research_on_optimizer/round5/Adam/config_9
train_batch: 128
weight_decay: 0.0005
