dataset_path: /home/ubuntu/DeepLearningWorkshop/dataset/CIFAR-10/raw/
epochs: 2
eval_batch: 256
eval_steps: 50
lr: 0.0015202616106112577
model_layer: 18
momentum: 0.8765415584362729
num_classes: 10
optimizer_type: Nestrov
res_path: /home/ubuntu/DeepLearningWorkshop/results/research_on_optimizer/round2/Nestrov/config_3
train_batch: 128
