dataset_path: /home/ubuntu/DeepLearningWorkshop/dataset/CIFAR-10/raw/
epochs: 2
eval_batch: 256
eval_steps: 50
lr: 0.026895261610611256
model_layer: 18
momentum: 0.8132082251029396
num_classes: 10
optimizer_type: Nestrov
res_path: /home/ubuntu/DeepLearningWorkshop/results/research_on_optimizer/round2/Nestrov/config_4
train_batch: 128
