dataset_path: /home/jingqi/DeepLearningWorkshop/dataset/CIFAR-10/raw/
epochs: 10
eval_batch: 256
eval_steps: 50
lr: 0.020945878782474985
model_layer: 50
num_classes: 10
optimizer_type: NAdam
res_path: /home/jingqi/DeepLearningWorkshop/results/research_on_optimizer/NAdam/config_7
train_batch: 128
