dataset_path: /home/jingqi/DeepLearningWorkshop/dataset/CIFAR-10/raw/
epochs: 10
eval_batch: 256
eval_steps: 50
lr: 0.004735459756036539
model_layer: 50
num_classes: 10
optimizer_type: AdamW
res_path: /home/jingqi/DeepLearningWorkshop/results/research_on_optimizer/round2/AdamW/config_5
train_batch: 128
